config/routes.rb
Rails.application.routes.draw do
  root to: redirect("/monitored_endpoints")

  resources :monitored_endpoints do
    resources :daily_details, only: %i[ show ], param: :date, module: :monitored_endpoints
  end

  get "up" => "rails/health#show", as: :rails_health_check
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/monitored_endpoint.rb
class MonitoredEndpoint < ApplicationRecord
  include Scheduable, Checkable

  has_many :checks, dependent: :destroy

  enum :status, %w[ pending in_progress ].index_by(&:itself), default: :pending

  validates :title, presence: true
  validates :url, presence: true, format: { with: URI.regexp, message: "should be valid url" }
  validates :threshold, presence: true, numericality: { only_integer: true, greater_than: 0 }
  validates :interval, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 1.minute, less_than_or_equal_to: 1.hour }

  broadcasts_refreshes

  def statuses_by_day(from:, to:)
    checks.group_by_day(:created_at, range: from..to, series: true)
      .maximum(:status)
      .transform_values { |v| v.nil? ? nil : MonitoredEndpoint::Check.statuses.key(v) }
  end

  def average_latency(from:, to:)
    checks.group_by_day(:created_at, range: from..to, series: true)
      .average(:latency)
      .transform_values { |v| v.nil? ? nil : v.round }
  end

  def failed_response_counts(from:, to:)
    checks.group_by_day(:created_at, reverse: true, range: from..to)
      .count("CASE WHEN monitored_endpoint_checks.status IN (1, 2) THEN 1 END")
  end

  def response_status
    checks.chronologically.last&.status
  end
end

app/models/monitored_endpoint/check.rb
class MonitoredEndpoint::Check < ApplicationRecord
  belongs_to :monitored_endpoint

  enum :status, { operational: 0, degraded: 1, incident: 2 }, default: :operational

  scope :by_date, ->(date) { where(created_at: date.all_day) }
  scope :chronologically, -> { order created_at: :asc, id: :asc }
end

app/models/monitored_endpoint/checkable.rb
module MonitoredEndpoint::Checkable
  extend ActiveSupport::Concern

  def check_now
    return if in_progress?
    in_progress!

    response = perform_request

    transaction do
      checks.create!(latency: response[:latency], response_code: response[:code], status: response[:status])
      pending!
    end
  rescue ActiveRecord::StaleObjectError
    reload
    retry
  rescue => e
    pending!
    raise e
  end

  def check_later
    MonitoredEndpoint::CheckJob.perform_later(self)
  end

  private

    def perform_request
      start_time = MonitoredEndpoint::Checkable.gettime
      response = HTTP.get(url)
      end_time = MonitoredEndpoint::Checkable.gettime

      latency = (end_time - start_time).in_milliseconds
      status = get_status(response.code, latency, threshold)

      { code: response.code, latency:, status: }
    rescue => e
      { code: nil, latency: nil, status: :incident }
    end

    def get_status(response_code, latency, threshold)
      return :incident unless response_code && response_code.between?(200, 399)

      return :degraded if latency > threshold

      :operational
    end

    def self.gettime
      Process.clock_gettime(Process::CLOCK_MONOTONIC)
    end
end

app/models/monitored_endpoint/report.rb
module MonitoredEndpoint::Report
  extend ActiveSupport::Concern

  included do
    after_commit :flush_cache, if: -> { ready? && status_previously_changed? }
  end

  def average_response_time
    checks.
      group_by_day(:created_at, reverse: true, range: (Date.today - 6)..Date.today).
      average(:latency)
  end

  def total_checks_counts
    checks.
      group_by_day(:created_at, reverse: true, range: (Date.today - 6)..Date.today).
      count
  end

  def incedent_counts
    checks.
      group_by_day(:created_at, reverse: true, range: (Date.today - 6)..Date.today).
      count("CASE WHEN monitored_endpoint_checks.response_code NOT BETWEEN 200 AND 399 THEN 1 END")
  end

  def degraded_counts
    checks.
      group_by_day(:created_at, reverse: true, range: (Date.today - 6)..Date.today).
      joins(:monitored_endpoint).
      count <<~SQL
              CASE
              WHEN (monitored_endpoint_checks.response_code BETWEEN 200 AND 399)
              AND  (monitored_endpoint_checks.latency > monitored_endpoints.threshold)
              THEN
                1
              END
            SQL
  end

  def cached_average_response_time
    Rails.cache.fetch([self.class.name, id, "average_response_time"]) { average_response_time }
  end

  def cached_total_checks_counts
    Rails.cache.fetch([self.class.name, id, "total_checks_counts"]) { total_checks_counts }
  end

  def cached_incedent_counts
    Rails.cache.fetch([self.class.name, id, "incedent_counts"]) { incedent_counts }
  end

  def cached_degraded_counts
    Rails.cache.fetch([self.class.name, id, "degraded_counts"]) { degraded_counts }
  end

  def flush_cache
    Rails.cache.delete([self.class.name, id, "average_response_time"])
    Rails.cache.delete([self.class.name, id, "total_checks_counts"])
    Rails.cache.delete([self.class.name, id, "incedent_counts"])
    Rails.cache.delete([self.class.name, id, "degraded_counts"])
  end
end

app/models/monitored_endpoint/scheduable.rb
module MonitoredEndpoint::Scheduable
  extend ActiveSupport::Concern

  included do
    scope :ready_for_launch, -> { pending.where("next_launch_at <= ?", Time.current) }

    before_save :calc_launch_time
  end

  private

    def calc_launch_time
      if pending?
        self.next_launch_at = Time.current + interval.seconds
      else
        self.next_launch_at = nil
      end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/concerns/monitored_endpoint_scoped.rb
module MonitoredEndpointScoped
  extend ActiveSupport::Concern

  included do
    before_action :set_monitored_endpoint
  end

  private
    def set_monitored_endpoint
      @monitored_endpoint = MonitoredEndpoint.find(params.expect(:monitored_endpoint_id))
    end
end

app/controllers/monitored_endpoints/daily_details_controller.rb
class MonitoredEndpoints::DailyDetailsController < ApplicationController
  include MonitoredEndpointScoped
  before_action :set_date, only: %i[ show ]

  def show
    @checks = @monitored_endpoint.checks.by_date(@date).not_operational.chronologically
  end

  private
    def set_date
      @date = Date.parse(params.expect(:date))
    end
end

app/controllers/monitored_endpoints_controller.rb
class MonitoredEndpointsController < ApplicationController
  before_action :set_monitored_endpoint, only: %i[ edit update destroy ]

  def index
    @monitored_endpoints = MonitoredEndpoint.all
  end

  def new
    @monitored_endpoint = MonitoredEndpoint.new
  end

  def edit
  end

  def create
    @monitored_endpoint = MonitoredEndpoint.new(monitored_endpoint_params)

    respond_to do |format|
      if @monitored_endpoint.save
        format.html { redirect_to monitored_endpoints_path, notice: "Monitored endpoint was successfully created." }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @monitored_endpoint.update(monitored_endpoint_params)
        format.html { redirect_to monitored_endpoints_path, notice: "Monitored endpoint was successfully updated." }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @monitored_endpoint.destroy!

    respond_to do |format|
      format.html { redirect_to monitored_endpoints_path, status: :see_other, notice: "Monitored endpoint was successfully destroyed." }
    end
  end

  private
    def set_monitored_endpoint
      @monitored_endpoint = MonitoredEndpoint.find(params.expect(:id))
    end

    def monitored_endpoint_params
      params.expect(monitored_endpoint: [:title, :url, :threshold, :interval])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def field_errors(object, field)
    return if object.errors[field].empty?

    content_tag :div, class: "error" do
      object.errors[field].join(", ")
    end
  end
end

app/helpers/monitored_endpoints/daily_details_helper.rb
module MonitoredEndpoints::DailyDetailsHelper
end

app/helpers/monitored_endpoints_helper.rb
module MonitoredEndpointsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Status Monitoring" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= turbo_refreshes_with(method: :morph, scroll: :preserve) %>
    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="container">
      <%= yield %>
    </main>
  </body>
</html>

app/views/monitored_endpoints/_form.html.erb
<%= form_with(model: monitored_endpoint, class: "w-full") do |form| %>

  <%= form.label :title %>
  <%= form.text_field :title, placeholder: "Title" %>
  <%= field_errors(form.object, :title) %>

  <%= form.label :url %>
  <%= form.url_field :url, placeholder: "Url" %>
  <%= field_errors(form.object, :url) %>

  <%= form.label :threshold %>
  <%= form.number_field :threshold, placeholder: "Threshold" %>
  <%= field_errors(form.object, :threshold) %>

  <%= form.label :interval %>
  <%= form.number_field :interval, placeholder: "Interval" %>
  <%= field_errors(form.object, :interval) %>

  <div class="flex items-center gap">
    <%= form.submit class: "btn btn-primary" %>
    <%= link_to "Back", monitored_endpoints_path %>
  </div>
<% end %>

app/views/monitored_endpoints/_monitored_endpoint.html.erb
<div class="flex gap">
  <%= monitored_endpoint.url %> (Threshold: <%= monitored_endpoint.threshold %>ms, Interval: <%= monitored_endpoint.interval %> sec)
  <%= link_to "Edit", edit_monitored_endpoint_path(monitored_endpoint) %>
  <%= link_to "Delete", monitored_endpoint_path(monitored_endpoint), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } %>
</div>

<div class="uptime-history">
  <% monitored_endpoint.statuses_by_day(from: 60.days.ago.to_date, to: Date.current).each do |date, status| %>
    <% if status %>
      <div contents data-controller="popover" data-action="mouseenter->popover#debouncedShow mouseleave->popover#debouncedHide">
        <a href="" class="uptime-history__day uptime-history__day--<%= status %>" data-popover-target="trigger">
          <div popover="hint" class="popover popover--block-end-start" data-popover-target="content" role="dialog">
            <%= turbo_frame_tag "details-#{date}", src: monitored_endpoint_daily_detail_path(monitored_endpoint, date), loading: :lazy %>
          </div>
        </a>
      </div>
    <% else %>
      <div href="" class="uptime-history__day uptime-history__day--<%= status %>"></div>
    <% end %>
  <% end %>
</div>

<div>
  <h3>Averange latency, ms</h3>
  <%= area_chart monitored_endpoint.average_latency(from: 60.days.ago.to_date, to: Date.current) %>
</div>

<div>
  <h3>Failed response count</h3>
  <%= area_chart monitored_endpoint.failed_response_counts(from: 60.days.ago.to_date, to: Date.current) %>
</div>

app/views/monitored_endpoints/daily_details/show.html.erb
<%= turbo_frame_tag "details-#{@date}" do %>
  <div class="day-details">
    <header>
      <%= l @date %>
    </header>
    <% if @checks.present? %>
      <% @checks.each do |check| %>
        <div><%= l check.created_at, format: :short %>: <%= check.status %></div>
      <% end %>
    <% else %>
      Uptime: 100%
    <% end %>
  </div>
<% end %>

app/views/monitored_endpoints/edit.html.erb
<% content_for :title, "Editing monitored endpoint" %>

<h1>Edit</h1>

<%= render "form", monitored_endpoint: @monitored_endpoint %>

app/views/monitored_endpoints/index.html.erb
<% turbo_refreshes_with method: :morph, scroll: :preserve %>
<% @monitored_endpoints.each do |monitored_endpoint| %>
  <%= turbo_stream_from monitored_endpoint %>
<% end %>

<% content_for :title, "Monitored endpoints" %>

<div class="flex justify-between items-center">
  <h1>Monitored endpoints</h1>
  <%= link_to "New monitored endpoint", new_monitored_endpoint_path %>
</div>

<div id="monitored_endpoints">
  <% if @monitored_endpoints.any? %>
    <% @monitored_endpoints.each do |monitored_endpoint| %>
      <div>

        <div class="flex justify-between items-center">
          <h2><%= monitored_endpoint.title %></h2>
          <%= monitored_endpoint.response_status %>
        </div>

        <%= render monitored_endpoint %>
      </div>
    <% end %>
  <% else %>
    <p>No monitored endpoints found.</p>
  <% end %>
</div>

app/views/monitored_endpoints/new.html.erb
<% content_for :title, "New monitored endpoint" %>

<div class="flex justify-between items-center">
  <h1>Add new endpoint</h1>
  <%= link_to "Back", monitored_endpoints_path %>
</div>

<%= render "form", monitored_endpoint: @monitored_endpoint %>

app/views/pages/home.html.erb
<div>
  <h1 class="font-bold text-4xl">Welcome</h1>

  Go to <%= link_to "Monitored endpoints", monitored_endpoints_path, class: "link" %>
</div>